name: CI Workflow
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest]  
    name: build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build  
  lint:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest]  
    name: lint
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go install golang.org/x/lint/golint@v0.0.0-20201208152925-83fdc39ff7b5
          golint -set_exit_status ./...
          go vet ./...
  tests:
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest]  
    name: tests
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go install github.com/mfridman/tparse@latest
          go test -v -race -cover -json ./... | $(go env GOPATH)/bin/tparse -all
